### ISSUE TITLE
Transaction keeps getting rejected

### ISSUE THREAD

**Issue by Wi11yWank3r** [bitcoinpostquantum/electrumpq#2]
Whatever transaction I'm trying to do it keeps getting rejected. error: {'code': 1, 'message': 'the transaction was rejected by network rules.\n\n64: non-bpq-tx\n[01000000000101d94fandetc...

**Comment by noahanhao** [comment]
Please show the full raw transaction (01000000000101d94fandetc...)

**Comment by Wi11yWank3r** [comment]
error: {'code': 1, 'message': 'the transaction was rejected by network rules.\n\n64: non-bpq-tx\n[01000000000101731426f4667630d112b54be43dce95805b49ee255757cc107b981ba5a9fc26c30000000000fdffffff01e8030000000000001976a9148017a6ffef0d50d92667dc0bdec11418060035e388ac02483045022100f9b4e9cd6a8b4b2566f27c9804a05e43d147eae36dc653348e9b95f15b21783e022058749df1c2d0c104e018204dc26feab7300f62537120080c02f0b96d77c6431c012103e82a3a4282da4fb7ea6c751f2aead9582e02e5a6837187509134d7ddf15e4dbac2ee0800]'}

**Comment by noahanhao** [comment]
The problem is that you try to spend coins to a legacy Bitcoin 160-bit address (76 a9 14 8017a6ffef0d50d92667dc0bdec11418060035e3 88 ac). In Bitcoin Post-Quantum you have to create post-quantum address (starts with pq1 in mainnet or tq1 in testnet), then you can send coins to this pq-address.
Please follow the steps in the guidelines:
1) create pq-address: https://bitcoinpq.github.io/#electrumpq
2) claim your forked coins: https://bitcoinpq.github.io/#protect
