### ISSUE TITLE
synchronizing... forever

### ISSUE THREAD

**Issue by douchebanner** [bitcoinpostquantum/electrumpq#3]
it says its connected to 2 nodes but im stuck at block height 591053.
its the portable electrum, tried on 2 different computers and the 2 servers.

**Comment by noahanhao** [comment]
Block #591053 was the newest block at the moment of your message:
https://explorer.mainnet.bitcoinpq.org/block-height/591053 
Timestamp (utc) | 2019-08-01 08:12:45

Please could you check again and compare best block height via https://explorer.mainnet.bitcoinpq.org/ ?

**Comment by douchebanner** [comment]
![Clipboard01](https://user-images.githubusercontent.com/31779233/62323510-bb836780-b4a7-11e9-9629-d7621b42bc4c.png)
shouldn't it say synchronized? also i haven't received any transactions for a month and i should have some. 
should i try recovering from seed? maybe the wallet file is corrupted?

EDIT: i just tried an older backup and recovering from seed, all i get is "synchronizing..."
should i try a vpn? maybe the servers dont like my ip for whatever reason...

**Comment by noahanhao** [comment]
It shouldn't say synchronized, instead it must draw your balance there. I've tried portable electrumpq 4.0.0 in Windows 7 x64 and Windows 10 x64 and it works fine for me. Please try to take the following steps:
1) Check if your firewall or antivirus is blocking electrumpq
2) Delete "electrum_data" folder located near electrumpq-4.0.0-portable.exe

**Comment by noahanhao** [comment]
If it doesn't help, please let me know your address(es) so I can track your transactions and check if there something wrong which leads to the synchronization problem

**Comment by douchebanner** [comment]
tried the installer, disabled firewall and antiviurs, tried a vpn and also xubuntu vm

pq1

**Comment by noahanhao** [comment]
Please try again now. 
The problem is that ElectrumX server (that ElectrumXPQ is forked from) sends transactions history in 1 request, therefore a big history of transactions doesn't fit into the server limits (1,000,000 bytes in 1 request; and your address has 10405 tx). I've made a dirty fix in server configuration - just increased server limits to the value that should be enough (10,000,000 bytes). When ElectrumX developers will add pagination to this kind of requests, we will add it to ElectrumXPQ.

**Comment by douchebanner** [comment]
yup, that did it, thanks for the fix.
